server:
  port: 9007

feign:
  sentinel:
    enabled: true

spring:
  data:
    solr:
      host: http://localhost:8091/solr/user_vide_demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 
    username: 
    password: 

  application:
    name: nacos-supermarket-Solr-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      eager: true

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.example.po
  configuration:
    auto-mapping-behavior: full
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl