server:
  port: 9001

feign:
  sentinel:
    enabled: true

spring:
  application:
    name: nacos-supermarket-User-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      eager: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 
    username: 
    password: 

  redis:
    # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
    database: 1
    # redis服务器地址（默认为loaclhost）
    host: 127.0.0.1
    # redis端口（默认为6379）
    post: 6379
    # redis访问密码（默认为空）
    # redis连接超时时间（单位毫秒）
    timeout: 1000
    # redis连接池配置
#    pool:
#      # 最大可用连接数（默认为8，负数表示无限）
#      max-active: 8
#      # 最大空闲连接数（默认为8，负数表示无限）
#      max-idle: 8
#      # 最小空闲连接数（默认为0，该值只有为正数才有用）
#      min-idle: 0
#      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
#      max-wait: -1

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.example.po
  configuration:
    auto-mapping-behavior: full
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  endpoints:
    web:
      exposure:
        include: "*"

#mq:
#  config:
#    exchange: direct
#    queue: q11
#    routing: routingkey
# 设置 feign 客户端超时时间（OpenFeign 默认支持 ribbon）
ribbon:
  # 值的是建立连接所用的时间，使用与网络状态正常的情况，两端连接所用的时间
  ReadTimeout: 50000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectionTimeout: 50000
