server:
  port: 8087


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 
    username: 
    password: 

  application:
    name: nacos-supermarket-gif-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      eager: true

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.example.po
  configuration:
    auto-mapping-behavior: full
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  endpoints:
    web:
      exposure:
        include: "*"